IIETA/Controllers/CatigoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IIETA.Data;
using IIETA.Models;
using Microsoft.AspNetCore.Authorization;

namespace IIETA.Controllers
{
    public class CatigoriesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CatigoriesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Catigories
        public async Task<IActionResult> Index()
        {
              return _context.Catigorie != null ? 
                          View(await _context.Catigorie.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Catigorie'  is null.");
        }

        public async Task<IActionResult> Admin()
        {
            return _context.Catigorie != null ?
                        View(await _context.Catigorie.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Catigorie'  is null.");
        }


        // GET: Catigories/Details/5
        [Authorize]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Catigorie == null)
            {
                return NotFound();
            }

            var catigorie = await _context.Catigorie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (catigorie == null)
            {
                return NotFound();
            }

            return View(catigorie);
        }

        // GET: Catigories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Catigories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description,Type,Location,Total_cost,Act_cost,Is_agent")] Catigorie catigorie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(catigorie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(catigorie);
        }




        // GET: Catigories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var catigorie = await _context.Catigorie
        .Where(c => c.Id == id)
        .FirstOrDefaultAsync();

            if (catigorie == null)
            {
                return NotFound();
            }
            return View(catigorie);
        }

        // POST: Catigories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description,Type,Location,Total_cost,Act_cost,Is_agent")] Catigorie catigorie, int additionalCost)
        {
            if (catigorie == null)
            {
                return NotFound();
            }

/*            if (additionalCost < 0 )
            {
                ModelState.AddModelError("AdditionalCost", "Additional Cost must be a non-negative number.");
   }
            if (additionalCost > catigorie.Act_cost)
            {
                ModelState.AddModelError("AdditionalCost", "Additional Cost must be less than total.");         
            }*/

            if (ModelState.IsValid)
            {
                try
                {
                    catigorie.Act_cost += additionalCost; 

                    _context.Update(catigorie);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CatigorieExists(catigorie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }

            return View(nameof(Index));
        }




        // GET: Catigories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Catigorie == null)
            {
                return NotFound();
            }

            var catigorie = await _context.Catigorie
                .FirstOrDefaultAsync(m => m.Id == id);
            if (catigorie == null)
            {
                return NotFound();
            }

            return View(catigorie);
        }

        // POST: Catigories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Catigorie == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Catigorie'  is null.");
            }
            var catigorie = await _context.Catigorie.FindAsync(id);
            if (catigorie != null)
            {
                _context.Catigorie.Remove(catigorie);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CatigorieExists(int id)
        {
          return (_context.Catigorie?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

IIETA/Controllers/handleEmailsController.cs
 using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using IIETA.Data;
using IIETA.Models;

namespace IIETA.Controllers
{
    public class handleEmailsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public handleEmailsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: handleEmails
        public async Task<IActionResult> Index()
        {
              return _context.handleEmail != null ? 
                          View(await _context.handleEmail.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.handleEmail'  is null.");
        }

        // GET: handleEmails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.handleEmail == null)
            {
                return NotFound();
            }

            var handleEmail = await _context.handleEmail
                .FirstOrDefaultAsync(m => m.Id == id);
            if (handleEmail == null)
            {
                return NotFound();
            }

            return View(handleEmail);
        }

        // GET: handleEmails/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: handleEmails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,Message")] handleEmail handleEmail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(handleEmail);
                await _context.SaveChangesAsync();

                // Add a success message to TempData
                TempData["SuccessMessage"] = "Email has been successfully sent!";

                // Reset the form fields
                ModelState.Clear();
                handleEmail = new handleEmail(); // Create a new instance to clear the input fields


            }
            return View(handleEmail);
        }

        // GET: handleEmails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.handleEmail == null)
            {
                return NotFound();
            }

            var handleEmail = await _context.handleEmail.FindAsync(id);
            if (handleEmail == null)
            {
                return NotFound();
            }
            return View(handleEmail);
        }

        // POST: handleEmails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,Message")] handleEmail handleEmail)
        {
            if (id != handleEmail.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(handleEmail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!handleEmailExists(handleEmail.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(handleEmail);
        }

        // GET: handleEmails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.handleEmail == null)
            {
                return NotFound();
            }

            var handleEmail = await _context.handleEmail
                .FirstOrDefaultAsync(m => m.Id == id);
            if (handleEmail == null)
            {
                return NotFound();
            }

            return View(handleEmail);
        }

        // POST: handleEmails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.handleEmail == null)
            {
                return Problem("Entity set 'ApplicationDbContext.handleEmail'  is null.");
            }
            var handleEmail = await _context.handleEmail.FindAsync(id);
            if (handleEmail != null)
            {
                _context.handleEmail.Remove(handleEmail);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool handleEmailExists(int id)
        {
          return (_context.handleEmail?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

IIETA/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IIETA</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IIETA.styles.css" asp-append-version="true" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom box-shadow mb-3" style="background-color:#0C356A;">
            <div class="container-fluid">
                <img src="~/assets/logo.jpeg" style="height:100px;width:100px;border-radius:50%;" />
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">About</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Catigories" asp-action="Index">Our Causes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="handleEmails" asp-action="Create">Connect Us</a>
                        </li>
                                                <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Catigories" asp-action="Admin">Admin</a>
                        </li>
                    </ul>
                    <partial  name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container text-light">
        <main role="main" class="pb-3 text-light">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-color:#0C356A ;margin-bottom:0px;margin-top:50px">
        <div style="text-align: center;">
            <a href="#" style="color: #fff; margin-right: 10px;"><i class="bi bi-facebook"></i></a>
            <a href="#" style="color: #fff; margin-right: 10px;"><i class="bi bi-instagram"></i></a>
            <a href="#" style="color: #fff; margin-right: 10px;"><i class="bi bi-snapchat"></i></a>
            <a href="#" style="color: #fff;"><i class="bi bi-twitter"></i></a>
        </div>
        <div class="container text-light">
            &copy; 2023 - IIETA - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
        <div class="container text-light">
            this application is developed by : majed & naser 
        </div>

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>